// -----------------------------------------------------------------------------
// skewdct8.sv
// -----------------------------------------------------------------------------
// 8-point skew DCT-III matrix block, fixed-point, fully combinational.
//
// Mathematical meaning:
//   y[k] = sum_{j=0}^{7} C[k][j] * x[j]
//   C[k][j] = round( cos(j * theta_k) * 2^COEF_FRAC )
// where theta_k/pi are the ordered zeros of T_8(x) - cos(r*pi).
//
// For the default parameter set, r = 1/2, so this is the ordinary unscaled
// DCT-III_8 coefficient matrix.  For a true skew DCT used inside the recursive
// DCT64 decomposition, override C00..C77 with the coefficient set for the
// required r_i.
//
// Notes:
//   * Verilog-2001 compatible flattened interface.
//   * Output is rounded back after coefficient fractional bits are removed.
//   * If your top-level needs the paper's skew DCT-II, instantiate this module
//     with coefficients generated by scripts/skewdct8_coeff_gen.py --kind ii.
// -----------------------------------------------------------------------------

`ifndef SKEWDCT8_V
`define SKEWDCT8_V

module skewdct8 #(
    parameter integer DATA_W    = 16,
    parameter integer COEF_W    = 16,
    parameter integer COEF_FRAC = 14,
    parameter integer ACC_W     = 40,
    parameter integer OUT_W     = 24,
    parameter integer USE_COEFF_PORT = 0,

    // Default: Q14 coefficients for unscaled DCT-III_8, r = 1/2.
    parameter signed [COEF_W-1:0] C00 = 16'sd16384, C01 = 16'sd16069, C02 = 16'sd15137, C03 = 16'sd13623,
                                   C04 = 16'sd11585, C05 = 16'sd9102,  C06 = 16'sd6270,  C07 = 16'sd3196,
    parameter signed [COEF_W-1:0] C10 = 16'sd16384, C11 = 16'sd13623, C12 = 16'sd6270,  C13 = -16'sd3196,
                                   C14 = -16'sd11585,C15 = -16'sd16069,C16 = -16'sd15137,C17 = -16'sd9102,
    parameter signed [COEF_W-1:0] C20 = 16'sd16384, C21 = 16'sd9102,  C22 = -16'sd6270, C23 = -16'sd16069,
                                   C24 = -16'sd11585,C25 = 16'sd3196,  C26 = 16'sd15137, C27 = 16'sd13623,
    parameter signed [COEF_W-1:0] C30 = 16'sd16384, C31 = 16'sd3196,  C32 = -16'sd15137,C33 = -16'sd9102,
                                   C34 = 16'sd11585, C35 = 16'sd13623, C36 = -16'sd6270, C37 = -16'sd16069,
    parameter signed [COEF_W-1:0] C40 = 16'sd16384, C41 = -16'sd3196, C42 = -16'sd15137,C43 = 16'sd9102,
                                   C44 = 16'sd11585, C45 = -16'sd13623,C46 = -16'sd6270, C47 = 16'sd16069,
    parameter signed [COEF_W-1:0] C50 = 16'sd16384, C51 = -16'sd9102, C52 = -16'sd6270, C53 = 16'sd16069,
                                   C54 = -16'sd11585,C55 = -16'sd3196, C56 = 16'sd15137, C57 = -16'sd13623,
    parameter signed [COEF_W-1:0] C60 = 16'sd16384, C61 = -16'sd13623,C62 = 16'sd6270,  C63 = 16'sd3196,
                                   C64 = -16'sd11585,C65 = 16'sd16069, C66 = -16'sd15137,C67 = 16'sd9102,
    parameter signed [COEF_W-1:0] C70 = 16'sd16384, C71 = -16'sd16069,C72 = 16'sd15137, C73 = -16'sd13623,
                                   C74 = 16'sd11585, C75 = -16'sd9102, C76 = 16'sd6270,  C77 = -16'sd3196
)(
    input  signed [DATA_W-1:0] x0,
    input  signed [DATA_W-1:0] x1,
    input  signed [DATA_W-1:0] x2,
    input  signed [DATA_W-1:0] x3,
    input  signed [DATA_W-1:0] x4,
    input  signed [DATA_W-1:0] x5,
    input  signed [DATA_W-1:0] x6,
    input  signed [DATA_W-1:0] x7,
    output signed [OUT_W-1:0]  y0,
    output signed [OUT_W-1:0]  y1,
    output signed [OUT_W-1:0]  y2,
    output signed [OUT_W-1:0]  y3,
    output signed [OUT_W-1:0]  y4,
    output signed [OUT_W-1:0]  y5,
    output signed [OUT_W-1:0]  y6,
    output signed [OUT_W-1:0]  y7,
    input  signed [COEF_W-1:0] c_in [0:7][0:7]
);

    localparam signed [ACC_W-1:0] ROUND_BIAS = (COEF_FRAC == 0) ? {ACC_W{1'b0}} : ({{(ACC_W-1){1'b0}},1'b1} <<< (COEF_FRAC-1));

    wire signed [COEF_W-1:0] K00 = USE_COEFF_PORT ? c_in[0][0] : C00;
    wire signed [COEF_W-1:0] K01 = USE_COEFF_PORT ? c_in[0][1] : C01;
    wire signed [COEF_W-1:0] K02 = USE_COEFF_PORT ? c_in[0][2] : C02;
    wire signed [COEF_W-1:0] K03 = USE_COEFF_PORT ? c_in[0][3] : C03;
    wire signed [COEF_W-1:0] K04 = USE_COEFF_PORT ? c_in[0][4] : C04;
    wire signed [COEF_W-1:0] K05 = USE_COEFF_PORT ? c_in[0][5] : C05;
    wire signed [COEF_W-1:0] K06 = USE_COEFF_PORT ? c_in[0][6] : C06;
    wire signed [COEF_W-1:0] K07 = USE_COEFF_PORT ? c_in[0][7] : C07;
    wire signed [COEF_W-1:0] K10 = USE_COEFF_PORT ? c_in[1][0] : C10;
    wire signed [COEF_W-1:0] K11 = USE_COEFF_PORT ? c_in[1][1] : C11;
    wire signed [COEF_W-1:0] K12 = USE_COEFF_PORT ? c_in[1][2] : C12;
    wire signed [COEF_W-1:0] K13 = USE_COEFF_PORT ? c_in[1][3] : C13;
    wire signed [COEF_W-1:0] K14 = USE_COEFF_PORT ? c_in[1][4] : C14;
    wire signed [COEF_W-1:0] K15 = USE_COEFF_PORT ? c_in[1][5] : C15;
    wire signed [COEF_W-1:0] K16 = USE_COEFF_PORT ? c_in[1][6] : C16;
    wire signed [COEF_W-1:0] K17 = USE_COEFF_PORT ? c_in[1][7] : C17;
    wire signed [COEF_W-1:0] K20 = USE_COEFF_PORT ? c_in[2][0] : C20;
    wire signed [COEF_W-1:0] K21 = USE_COEFF_PORT ? c_in[2][1] : C21;
    wire signed [COEF_W-1:0] K22 = USE_COEFF_PORT ? c_in[2][2] : C22;
    wire signed [COEF_W-1:0] K23 = USE_COEFF_PORT ? c_in[2][3] : C23;
    wire signed [COEF_W-1:0] K24 = USE_COEFF_PORT ? c_in[2][4] : C24;
    wire signed [COEF_W-1:0] K25 = USE_COEFF_PORT ? c_in[2][5] : C25;
    wire signed [COEF_W-1:0] K26 = USE_COEFF_PORT ? c_in[2][6] : C26;
    wire signed [COEF_W-1:0] K27 = USE_COEFF_PORT ? c_in[2][7] : C27;
    wire signed [COEF_W-1:0] K30 = USE_COEFF_PORT ? c_in[3][0] : C30;
    wire signed [COEF_W-1:0] K31 = USE_COEFF_PORT ? c_in[3][1] : C31;
    wire signed [COEF_W-1:0] K32 = USE_COEFF_PORT ? c_in[3][2] : C32;
    wire signed [COEF_W-1:0] K33 = USE_COEFF_PORT ? c_in[3][3] : C33;
    wire signed [COEF_W-1:0] K34 = USE_COEFF_PORT ? c_in[3][4] : C34;
    wire signed [COEF_W-1:0] K35 = USE_COEFF_PORT ? c_in[3][5] : C35;
    wire signed [COEF_W-1:0] K36 = USE_COEFF_PORT ? c_in[3][6] : C36;
    wire signed [COEF_W-1:0] K37 = USE_COEFF_PORT ? c_in[3][7] : C37;
    wire signed [COEF_W-1:0] K40 = USE_COEFF_PORT ? c_in[4][0] : C40;
    wire signed [COEF_W-1:0] K41 = USE_COEFF_PORT ? c_in[4][1] : C41;
    wire signed [COEF_W-1:0] K42 = USE_COEFF_PORT ? c_in[4][2] : C42;
    wire signed [COEF_W-1:0] K43 = USE_COEFF_PORT ? c_in[4][3] : C43;
    wire signed [COEF_W-1:0] K44 = USE_COEFF_PORT ? c_in[4][4] : C44;
    wire signed [COEF_W-1:0] K45 = USE_COEFF_PORT ? c_in[4][5] : C45;
    wire signed [COEF_W-1:0] K46 = USE_COEFF_PORT ? c_in[4][6] : C46;
    wire signed [COEF_W-1:0] K47 = USE_COEFF_PORT ? c_in[4][7] : C47;
    wire signed [COEF_W-1:0] K50 = USE_COEFF_PORT ? c_in[5][0] : C50;
    wire signed [COEF_W-1:0] K51 = USE_COEFF_PORT ? c_in[5][1] : C51;
    wire signed [COEF_W-1:0] K52 = USE_COEFF_PORT ? c_in[5][2] : C52;
    wire signed [COEF_W-1:0] K53 = USE_COEFF_PORT ? c_in[5][3] : C53;
    wire signed [COEF_W-1:0] K54 = USE_COEFF_PORT ? c_in[5][4] : C54;
    wire signed [COEF_W-1:0] K55 = USE_COEFF_PORT ? c_in[5][5] : C55;
    wire signed [COEF_W-1:0] K56 = USE_COEFF_PORT ? c_in[5][6] : C56;
    wire signed [COEF_W-1:0] K57 = USE_COEFF_PORT ? c_in[5][7] : C57;
    wire signed [COEF_W-1:0] K60 = USE_COEFF_PORT ? c_in[6][0] : C60;
    wire signed [COEF_W-1:0] K61 = USE_COEFF_PORT ? c_in[6][1] : C61;
    wire signed [COEF_W-1:0] K62 = USE_COEFF_PORT ? c_in[6][2] : C62;
    wire signed [COEF_W-1:0] K63 = USE_COEFF_PORT ? c_in[6][3] : C63;
    wire signed [COEF_W-1:0] K64 = USE_COEFF_PORT ? c_in[6][4] : C64;
    wire signed [COEF_W-1:0] K65 = USE_COEFF_PORT ? c_in[6][5] : C65;
    wire signed [COEF_W-1:0] K66 = USE_COEFF_PORT ? c_in[6][6] : C66;
    wire signed [COEF_W-1:0] K67 = USE_COEFF_PORT ? c_in[6][7] : C67;
    wire signed [COEF_W-1:0] K70 = USE_COEFF_PORT ? c_in[7][0] : C70;
    wire signed [COEF_W-1:0] K71 = USE_COEFF_PORT ? c_in[7][1] : C71;
    wire signed [COEF_W-1:0] K72 = USE_COEFF_PORT ? c_in[7][2] : C72;
    wire signed [COEF_W-1:0] K73 = USE_COEFF_PORT ? c_in[7][3] : C73;
    wire signed [COEF_W-1:0] K74 = USE_COEFF_PORT ? c_in[7][4] : C74;
    wire signed [COEF_W-1:0] K75 = USE_COEFF_PORT ? c_in[7][5] : C75;
    wire signed [COEF_W-1:0] K76 = USE_COEFF_PORT ? c_in[7][6] : C76;
    wire signed [COEF_W-1:0] K77 = USE_COEFF_PORT ? c_in[7][7] : C77;

    wire signed [ACC_W-1:0] s0 =
        $signed(x0) * $signed(K00) + $signed(x1) * $signed(K01) +
        $signed(x2) * $signed(K02) + $signed(x3) * $signed(K03) +
        $signed(x4) * $signed(K04) + $signed(x5) * $signed(K05) +
        $signed(x6) * $signed(K06) + $signed(x7) * $signed(K07);

    wire signed [ACC_W-1:0] s1 =
        $signed(x0) * $signed(K10) + $signed(x1) * $signed(K11) +
        $signed(x2) * $signed(K12) + $signed(x3) * $signed(K13) +
        $signed(x4) * $signed(K14) + $signed(x5) * $signed(K15) +
        $signed(x6) * $signed(K16) + $signed(x7) * $signed(K17);

    wire signed [ACC_W-1:0] s2 =
        $signed(x0) * $signed(K20) + $signed(x1) * $signed(K21) +
        $signed(x2) * $signed(K22) + $signed(x3) * $signed(K23) +
        $signed(x4) * $signed(K24) + $signed(x5) * $signed(K25) +
        $signed(x6) * $signed(K26) + $signed(x7) * $signed(K27);

    wire signed [ACC_W-1:0] s3 =
        $signed(x0) * $signed(K30) + $signed(x1) * $signed(K31) +
        $signed(x2) * $signed(K32) + $signed(x3) * $signed(K33) +
        $signed(x4) * $signed(K34) + $signed(x5) * $signed(K35) +
        $signed(x6) * $signed(K36) + $signed(x7) * $signed(K37);

    wire signed [ACC_W-1:0] s4 =
        $signed(x0) * $signed(K40) + $signed(x1) * $signed(K41) +
        $signed(x2) * $signed(K42) + $signed(x3) * $signed(K43) +
        $signed(x4) * $signed(K44) + $signed(x5) * $signed(K45) +
        $signed(x6) * $signed(K46) + $signed(x7) * $signed(K47);

    wire signed [ACC_W-1:0] s5 =
        $signed(x0) * $signed(K50) + $signed(x1) * $signed(K51) +
        $signed(x2) * $signed(K52) + $signed(x3) * $signed(K53) +
        $signed(x4) * $signed(K54) + $signed(x5) * $signed(K55) +
        $signed(x6) * $signed(K56) + $signed(x7) * $signed(K57);

    wire signed [ACC_W-1:0] s6 =
        $signed(x0) * $signed(K60) + $signed(x1) * $signed(K61) +
        $signed(x2) * $signed(K62) + $signed(x3) * $signed(K63) +
        $signed(x4) * $signed(K64) + $signed(x5) * $signed(K65) +
        $signed(x6) * $signed(K66) + $signed(x7) * $signed(K67);

    wire signed [ACC_W-1:0] s7 =
        $signed(x0) * $signed(K70) + $signed(x1) * $signed(K71) +
        $signed(x2) * $signed(K72) + $signed(x3) * $signed(K73) +
        $signed(x4) * $signed(K74) + $signed(x5) * $signed(K75) +
        $signed(x6) * $signed(K76) + $signed(x7) * $signed(K77);

    function signed [OUT_W-1:0] round_shift;
        input signed [ACC_W-1:0] v;
        reg   signed [ACC_W-1:0] vb;
        begin
            // Symmetric rounding: add half-LSB for positive values, subtract for negative.
            if (COEF_FRAC == 0) begin
                vb = v;
            end else if (v[ACC_W-1]) begin
                vb = v - ROUND_BIAS;
            end else begin
                vb = v + ROUND_BIAS;
            end
            round_shift = vb >>> COEF_FRAC;
        end
    endfunction

    assign y0 = round_shift(s0);
    assign y1 = round_shift(s1);
    assign y2 = round_shift(s2);
    assign y3 = round_shift(s3);
    assign y4 = round_shift(s4);
    assign y5 = round_shift(s5);
    assign y6 = round_shift(s6);
    assign y7 = round_shift(s7);

endmodule

`endif
